// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/builder.html"
    | "/content-scripts/content.js"
    | "/content-scripts/element-picker.js"
    | "/content-scripts/quick-panel.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/libs/ort.min.js"
    | "/offscreen.html"
    | "/options.html"
    | "/popup.html"
    | "/sidepanel.html"
    | "/web-editor-v2.js"
    | "/welcome.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
